version: "2"

services:
 
  jenkins:
    image: campbel/jenkins:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "jenkins:/var/jenkins_home"
      - "${SWARM_CERT_PATH}:/etc/swarm/certs"
    environment:
      SWARM_HOST: ${SWARM_HOST}
      SWARM_CERT_PATH: /etc/swarm/certs

volumes:
  jenkins:
